[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_merkle_tree_example = "2e9Bh6JTg7kqFGaGXdGrbCop9E46Qcba6Xanf1G2iWE7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/wv/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
